[build]
command = 'hugo'
publish = 'public'

[build.environment]
HUGO_VERSION = '0.146.0'

[context]
[context.branch-deploy]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.deploy-preview]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.production]
[context.production.environment]
HUGO_ENV = 'production'

[[redirects]]
  from = "https://paulparedes.pe/*"
  to   = "https://www.paulparedes.pe/:splat"
  status = 301
  force  = true

[[redirects]]
  from = "http://paulparedes.pe/*"
  to   = "https://www.paulparedes.pe/:splat"
  status = 301
  force  = true

[[redirects]]
  from = "http://www.paulparedes.pe/*"
  to   = "https://www.paulparedes.pe/:splat"
  status = 301
  force  = true
